name: CI

on:
  push:
    branches-ignore:
      - master 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Semantic Release Dry Run 
        run: |
          npm i
          npm run release -- -b "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')" -d true
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
